#
# Executes commands at the start of an interactive session.

# PATH and envvars
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#d78700"
export GPG_TTY=$(tty)
export REPO_VATICLE_USERNAME=...
export REPO_VATICLE_PASSWORD=...
export ARTIFACT_USERNAME=$REPO_VATICLE_USERNAME
export ARTIFACT_PASSWORD=$REPO_VATICLE_PASSWORD

# Aliases
alias ls=exa
alias vim=nvim
alias cd=z
# Don't like it? Come kill me. 
alias nano=nvim

