#
# Executes commands at the start of an interactive session.

# PATH and envvars
export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
export PATH="/Users/james/Library/Python/3.9/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/openjdk@11/include"
export GPG_TTY=$(tty)
export REPO_VATICLE_USERNAME=...
export REPO_VATICLE_PASSWORD=...
export ARTIFACT_USERNAME=$REPO_VATICLE_USERNAME
export ARTIFACT_PASSWORD=$REPO_VATICLE_PASSWORD

# The next line updates PATH for the Google Cloud SDK.
if [ -f '$HOME/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '$HOME/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '$HOME/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '$HOME/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

export PATH="/usr/local/opt/openssl@3/bin:$PATH"

. "$HOME/.cargo/env"


# Aliases
alias ls=exa
alias vim=nvim
alias cd=z
# Don't like it? Come kill me. 
alias nano=nvim

