#
# Executes commands at the start of an interactive session.

# PATH and envvars
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#d78700"
export GPG_TTY=$(tty)
export REPO_VATICLE_USERNAME=...
export REPO_VATICLE_PASSWORD=...
export ARTIFACT_USERNAME=$REPO_VATICLE_USERNAME
export ARTIFACT_PASSWORD=$REPO_VATICLE_PASSWORD

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/Downloads/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/Downloads/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc"; fi

. "$HOME/.cargo/env"


# Aliases
alias ls=exa
alias vim=nvim
alias cd=z
# Don't like it? Come kill me. 
alias nano=nvim

